"""Ingest Tokyo's official 2026 foreign-resident CSV into D1-ready SQL.

The source CSV is published by the Tokyo Metropolitan Government. The parser is
intentionally tolerant of title rows, repeated headers, comma-formatted numbers,
and either UTF-8 or CP932 encoding.
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import re
import urllib.request
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Iterable, Sequence

SOURCE_ID = "tokyo_foreign_residents_2026_01"
SOURCE_URL = "https://www.toukei.metro.tokyo.lg.jp/gaikoku/2026/ga26ev0100.csv"
REFERENCE_DATE = "2026-01-01"

TOKYO_WARDS = {
    "千代田区": "chiyoda",
    "中央区": "chuo",
    "港区": "minato",
    "新宿区": "shinjuku",
    "文京区": "bunkyo",
    "台東区": "taito",
    "墨田区": "sumida",
    "江東区": "koto",
    "品川区": "shinagawa",
    "目黒区": "meguro",
    "大田区": "ota",
    "世田谷区": "setagaya",
    "渋谷区": "shibuya",
    "中野区": "nakano",
    "杉並区": "suginami",
    "豊島区": "toshima",
    "北区": "kita",
    "荒川区": "arakawa",
    "板橋区": "itabashi",
    "練馬区": "nerima",
    "足立区": "adachi",
    "葛飾区": "katsushika",
    "江戸川区": "edogawa",
}


@dataclass(frozen=True)
class WardDemographic:
    ward_id: str
    ward_name_ja: str
    foreign_residents: int
    reference_date: str = REFERENCE_DATE
    source_url: str = SOURCE_URL


def decode_csv(payload: bytes) -> str:
    for encoding in ("utf-8-sig", "cp932", "shift_jis"):
        try:
            return payload.decode(encoding)
        except UnicodeDecodeError:
            continue
    raise ValueError("Could not decode source CSV as UTF-8 or CP932")


def _clean(cell: str) -> str:
    return cell.replace("\u3000", " ").strip()


def _parse_integer(cell: str) -> int | None:
    value = _clean(cell).replace(",", "")
    if not value or value in {"-", "—", "…"}:
        return None
    if not re.fullmatch(r"[+-]?\d+", value):
        return None
    return int(value)


def parse_ward_demographics(text: str) -> list[WardDemographic]:
    rows = list(csv.reader(io.StringIO(text)))
    records: list[WardDemographic] = []
    seen: set[str] = set()

    for row in rows:
        cleaned = [_clean(cell) for cell in row]
        ward_position = next(
            ((index, TOKYO_WARDS[cell], cell) for index, cell in enumerate(cleaned) if cell in TOKYO_WARDS),
            None,
        )
        if ward_position is None:
            continue

        index, ward_id, ward_name = ward_position
        total = next((_parse_integer(cell) for cell in cleaned[index + 1 :] if _parse_integer(cell) is not None), None)
        if total is None:
            raise ValueError(f"No total foreign-resident count found for {ward_name}")
        if ward_id in seen:
            continue

        seen.add(ward_id)
        records.append(
            WardDemographic(
                ward_id=ward_id,
                ward_name_ja=ward_name,
                foreign_residents=total,
            )
        )

    if not records:
        raise ValueError("No Tokyo special-ward rows were found in the source CSV")
    return records


def fetch_source(url: str = SOURCE_URL, timeout: int = 30) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "Metropolis-open-data-pipeline/0.1"})
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return response.read()


def _sql_string(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_sql(records: Sequence[WardDemographic], ingested_at: str) -> str:
    statements = [
        "-- Generated by pipelines/sources/tokyo_foreign_residents.py",
        "BEGIN TRANSACTION;",
    ]
    for record in records:
        statements.append(
            "INSERT INTO ward_demographics "
            "(ward_id, foreign_residents, reference_date, source_url, ingested_at) VALUES "
            f"({_sql_string(record.ward_id)}, {record.foreign_residents}, "
            f"{_sql_string(record.reference_date)}, {_sql_string(record.source_url)}, "
            f"{_sql_string(ingested_at)}) "
            "ON CONFLICT(ward_id) DO UPDATE SET "
            "foreign_residents=excluded.foreign_residents, "
            "reference_date=excluded.reference_date, "
            "source_url=excluded.source_url, "
            "ingested_at=excluded.ingested_at;"
        )
    statements.append("COMMIT;")
    return "\n".join(statements) + "\n"


def write_outputs(records: Sequence[WardDemographic], output_dir: Path, ingested_at: str) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    payload = {
        "sourceId": SOURCE_ID,
        "referenceDate": REFERENCE_DATE,
        "ingestedAt": ingested_at,
        "records": [asdict(record) for record in records],
    }
    (output_dir / "tokyo_foreign_residents_2026_01.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (output_dir / "tokyo_foreign_residents_2026_01.sql").write_text(
        render_sql(records, ingested_at),
        encoding="utf-8",
    )


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, help="Use a local CSV instead of downloading the source")
    parser.add_argument("--output-dir", type=Path, default=Path("data/processed"))
    args = parser.parse_args(list(argv) if argv is not None else None)

    payload = args.input.read_bytes() if args.input else fetch_source()
    records = parse_ward_demographics(decode_csv(payload))
    ingested_at = datetime.now(UTC).replace(microsecond=0).isoformat()
    write_outputs(records, args.output_dir, ingested_at)
    print(f"Wrote {len(records)} ward records to {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
